Post a new comment to an existing article functionality
AnnaTas77/nc-news-frontend-project pull request #6
Opened 2023-07-19 08:26 UTC by AnnaTas77

2023-07-19 10:35 UTC, NRMSMITH requested changes
Have a rethink about how the user sees they've made a mistake :D

2023-07-19 10:35 UTC, NRMSMITH commented on src/components/CommentAdder.jsx
> +                    onChange={(event) => {
I would suggest extrating this function out for readability :)

2023-07-19 10:35 UTC, NRMSMITH commented on src/components/CommentAdder.jsx
> +    console.log("newComment", newComment);
please remove logs! :)

2023-07-19 10:35 UTC, NRMSMITH commented on src/components/CommentAdder.jsx
> +                console.log(err);
so this console log doesn't really serve the user - maybe perhaps you could set a boolean state to indicate if there is an error, and then conditionally render a message to the user when there is an error?

2023-07-20 08:34 UTC, xViolaine approved these changes
Great job taking the given feedback on board!

2023-07-20 08:36 UTC, merged